init github action
GDG-Nantes/devfest2020-landing pull request #1
Opened 2020-02-12 20:28 UTC by ArtyMaury

2020-02-12 21:58 UTC, ArtyMaury commented
@xavmarc @jlandure ça tourne

2020-02-13 08:42 UTC, jlandure requested changes

2020-02-13 08:42 UTC, jlandure commented on public/app.yaml
> +instance_class: F1
inutile cette ligne

2020-02-13 08:42 UTC, jlandure commented on public/app.yaml
> +    require_matching_file: false
ça sert ça ? 🤔

2020-02-13 08:42 UTC, jlandure commented on public/app.yaml
> +automatic_scaling:
inutile ce bloc!

2020-02-13 08:42 UTC, jlandure commented on public/app.yaml
> +network: {}
inutile cette ligne! 👍

2020-02-16 15:09 UTC, ArtyMaury commented
Ouais j'ai pas trop regardé le app.yaml encore, j'avais repris celui de ton projet dummy.

2020-02-16 15:21 UTC, merged